version: '3.11'

services:
  djangoapp:
    build: .
    container_name: django-app
    command:
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 &&
      python manage.py search_index --rebuild"
    depends_on:
      - elasticsearch
#      - elasticsearch_test
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
     - custom-network
    ports:
      - 8000:8000
#    volumes:
#      - .:/app

  elasticsearch:
    container_name: elasticsearch-cn
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
#      - boostrap.memory_lock=true
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    networks:
     - custom-network
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana-cn
    depends_on:
      - elasticsearch
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    image: docker.elastic.co/kibana/kibana:7.17.9
    networks:
     - custom-network
    ports:
      - 5601:5601

#  elasticsearch_test:
#    container_name: elasticsearch-test-cn
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#      # - boostrap.memory_lock=true
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
#    networks:
#      - docker-testing-cluster
#    ports:
#      - 9200:9200
#      - 9300:9300

networks:
  custom-network: