# Generated by Django 4.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PypiPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=64)),
                ("author_email", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=16)),
            ],
        ),
    ]
